### ISSUE TITLE
Map unusably slow.

### ISSUE THREAD

**Issue by CodeLeopard** [carsakiller/Carsas-Companion#74]
With the addition of the new Arid Island the performance of the map in both Firefox and Chromium is now on the order of seconds per frame.

Perhaps WebGL can solve this if the Canvas can't be made to go faster?

**Comment by CrazyFluffyPony** [comment]
I would say the current implementation is sub optimal, but not critically bad (since this problem only happens on tiny zoom levels and with the recently added hundreds of vehicles).

Note: this feature is quite standalone from the rest of the software, so it can be replaced quite easily without compatibility problems.
Note 2: rewriting this will take quite some time.

**Comment by CrazyFluffyPony** [comment]
Test results (for tiny zoom levels):
increasing tile size > 200px slows down map performance
decreasing tile size <100px does not improve map performance 

Map Marker improvement:
* we should not draw markers outside of visible map area
* we should implement #44

Possible Tiles improvement:
merge together multiple tiles (e.g. 9 or 16) so the amount of calls to img.loadData() is lower (because that seems to slow down)

**Comment by CrazyFluffyPony** [comment]
done
