### ISSUE TITLE
Connecting problems (brief guideance request)

### ISSUE THREAD

**Issue by Sedrowow** [carsakiller/Carsas-Companion#79]
Hello, I have (kind of) problems connecting the companion app to a remote Server
The server is hosted on ZAP-Hosting, while the companion web server runs on my PC at home (port forwarding is already done and functional).

As far as I know, I have to edit something in the "script.lua" file. But what exactly? HTTP_GET_API_URL: has already something in it, do I need to put the IP in front of it? (seems like the HTTP data request (but what can I write after data=...? Are these words underneath the URL and if so: how can I add them?))

At the least few lines is also a URL thing. (named URL="?"). Does it automatically get assigned with the HTTP_GET_API_URL, or do I need to change this?

This would be everything I want to know and would be happy about an answer

Thanks in Advance :-)

**Comment by CrazyFluffyPony** [comment]
Stormworks only allows to talk to localhost (the server hosted by zap hosting).
You would need an application running on the server that proxies port 3367 towards the public IP of your home (any port you want to), and then tell your router to forward that port to your pc running the companion (target port 3367)

You would need access to the terminal or remote desktop connection in order to be able to install a proxy software.
